// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAanuWxPpEpnLQf30-5_tgpu-dLiXv4R1k',
    appId: '1:229109371607:web:175ff7c2d65f1440ba1692',
    messagingSenderId: '229109371607',
    projectId: 'posapp-acf2c',
    authDomain: 'posapp-acf2c.firebaseapp.com',
    storageBucket: 'posapp-acf2c.firebasestorage.app',
    measurementId: 'G-XR7DBSMP9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQl7xIDBC-_VoiBNPm_NMGpf3sXjzp-dA',
    appId: '1:229109371607:android:da26ad7321fec6ccba1692',
    messagingSenderId: '229109371607',
    projectId: 'posapp-acf2c',
    storageBucket: 'posapp-acf2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSLUEydSIevuOxmRreuTXLHa6CGecvgEY',
    appId: '1:229109371607:ios:26f40d87a8a6a81eba1692',
    messagingSenderId: '229109371607',
    projectId: 'posapp-acf2c',
    storageBucket: 'posapp-acf2c.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSLUEydSIevuOxmRreuTXLHa6CGecvgEY',
    appId: '1:229109371607:ios:26f40d87a8a6a81eba1692',
    messagingSenderId: '229109371607',
    projectId: 'posapp-acf2c',
    storageBucket: 'posapp-acf2c.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAanuWxPpEpnLQf30-5_tgpu-dLiXv4R1k',
    appId: '1:229109371607:web:5dc99edf77dfca84ba1692',
    messagingSenderId: '229109371607',
    projectId: 'posapp-acf2c',
    authDomain: 'posapp-acf2c.firebaseapp.com',
    storageBucket: 'posapp-acf2c.firebasestorage.app',
    measurementId: 'G-FZE9GVBLWB',
  );
}
